import {seedPlaces,seedEvents} from "./data/seed.js";
import {kudagoPlaces,kudagoEvents} from "./data/kudago.generated.js";
import {generateDates,replacePlanItem,planRows,formatMoney,formatDuration} from "./engine-v14.js?v=final3";

const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const FILTERS_KEY="1001dates.filters.v10", PROFILE_KEY="1001dates.profile.v10";
const DEFAULTS={duration:180,budget:7000,vibes:["romantic"],zone:"any",time:"19:00",food:true,useEvents:true,indoorOnly:false,noBars:false,avoidVisited:true,adventure:"balanced"};
const VIBE_LABELS={romantic:"Романтично",fun:"Весело",unusual:"Необычно",calm:"Спокойно",active:"Активно"};
const ZONES={any:"Вся Москва",center:"Центр",city:"Москва-Сити",vdnh:"ВДНХ / Останкино",west:"Запад",south:"Юг",east:"Восток"};
const FOCUSABLE='a[href],button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])';
let state={...DEFAULTS,...loadJSON(FILTERS_KEY,{})}; if(!Array.isArray(state.vibes)||!state.vibes.length)state.vibes=["romantic"];
let profile=normalizeProfile(loadJSON(PROFILE_KEY,{})),latestPlans=[],activePlanIndex=null,activeFilters=null,variationSeed=0,currentAnchor=null,inviteTheme="warm",inviteReveal="secret",focusStack=[];
const places=dedupe([...seedPlaces,...kudagoPlaces].map(sanitize)),events=dedupe([...seedEvents,...kudagoEvents].map(sanitize));

function loadJSON(k,f){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}}
function normalizeProfile(r){return{favoritePlans:Array.isArray(r.favoritePlans)?r.favoritePlans.slice(0,40):[],history:Array.isArray(r.history)?r.history.slice(0,30):[],favoriteItems:r.favoriteItems&&typeof r.favoriteItems==="object"?r.favoriteItems:{},dislikedItemIds:Array.isArray(r.dislikedItemIds)?r.dislikedItemIds.slice(0,150):[],recentlyShownItemIds:Array.isArray(r.recentlyShownItemIds)?r.recentlyShownItemIds.slice(0,90):[]}}
function persist(){localStorage.setItem(FILTERS_KEY,JSON.stringify({duration:state.duration,budget:state.budget,vibes:state.vibes,zone:state.zone,time:state.time,food:state.food,useEvents:state.useEvents,indoorOnly:state.indoorOnly,noBars:state.noBars,avoidVisited:state.avoidVisited,adventure:state.adventure}))}
function saveProfile(){localStorage.setItem(PROFILE_KEY,JSON.stringify(profile));syncBadge()}
function isURL(v){try{const u=new URL(v);return /^https?:$/.test(u.protocol)}catch{return false}}
function sanitize(i){return{...i,sourceUrl:isURL(i.sourceUrl)?i.sourceUrl:null,officialUrl:isURL(i.officialUrl)?i.officialUrl:null}}
function imageOK(v){return isURL(v)&&!/logo|poster|banner|afisha|афиш|sprite|icon/i.test(String(v))}
function dedupe(items){const m=new Map();for(const i of items){const k=`${i.category}:${i.title}`.toLowerCase(),p=m.get(k);if(!p||Number(i.quality||0)>Number(p.quality||0))m.set(k,i)}return[...m.values()]}
function esc(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function localISODate(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function shortDate(v){try{return new Intl.DateTimeFormat("ru-RU",{day:"numeric",month:"short"}).format(new Date(`${v}T12:00:00`)).replace(".","")}catch{return v}}
function humanDate(v){try{return new Intl.DateTimeFormat("ru-RU",{weekday:"long",day:"numeric",month:"long"}).format(new Date(`${v}T12:00:00`))}catch{return v}}
function shortMoney(v){return v>=900000?"любой бюджет":`до ${new Intl.NumberFormat("ru-RU").format(v)} ₽`}
function planKey(p){return `${p.template.id}:${p.items.map(i=>i.id).join("|")}`}
function stableNo(p){let h=2166136261;for(const c of planKey(p)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return String(((h>>>0)%1001)+1).padStart(4,"0")}
function visitedIds(){return[...new Set(profile.history.flatMap(e=>e.itemIds||[]))]}
function collectFilters(){return{date:state.date||localISODate(),time:state.time,duration:Number(state.duration),budget:Number(state.budget),vibes:[...state.vibes],zone:state.zone,food:state.food,useEvents:state.useEvents,indoorOnly:state.indoorOnly,noBars:state.noBars,avoidVisited:state.avoidVisited,adventure:state.adventure,likedItemIds:Object.keys(profile.favoriteItems),visitedItemIds:visitedIds(),dislikedItemIds:profile.dislikedItemIds,recentlyShownItemIds:profile.recentlyShownItemIds}}
function snapshotPlan(p,f){return{key:planKey(p),title:p.title,archetype:p.archetype?.label||"Свидание",totalMinutes:p.totalMinutes,totalCost:p.totalCost,itemIds:p.items.map(i=>i.id),itemTitles:p.items.map(i=>i.title),coverImage:imageOK(p.coverImage)?p.coverImage:null,date:f.date,time:f.time,filters:{...f},savedAt:new Date().toISOString()}}
function visibleOverlay(){return $$(".overlay.open").at(-1)||null}
function openOverlay(id){const o=$(id);if(!o)return;focusStack.push(document.activeElement);o.classList.add("open");o.setAttribute("aria-hidden","false");document.body.classList.add("modal-open");requestAnimationFrame(()=>$(FOCUSABLE,o)?.focus())}
function closeOverlay(id){const o=$(id);if(!o)return;o.classList.remove("open");o.setAttribute("aria-hidden","true");if(!visibleOverlay())document.body.classList.remove("modal-open");const target=focusStack.pop();requestAnimationFrame(()=>target?.focus?.())}
function trapFocus(e){const o=visibleOverlay();if(!o)return;if(e.key==="Escape"){e.preventDefault();closeOverlay(`#${o.id}`);return}if(e.key!=="Tab")return;const nodes=$$(FOCUSABLE,o).filter(n=>n.offsetParent!==null);if(!nodes.length){e.preventDefault();return}const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}
document.addEventListener("keydown",trapFocus);$$('.overlay').forEach(o=>o.addEventListener('click',e=>{if(e.target===o&&o.dataset.dismiss!=="false")closeOverlay(`#${o.id}`)}));$$('[data-close]').forEach(b=>b.addEventListener('click',()=>closeOverlay(b.dataset.close)));
function syncPressed(){$$('[data-duration],[data-budget],[data-vibe],[data-adventure],[data-theme],[data-reveal]').forEach(b=>b.setAttribute('aria-pressed',String(b.classList.contains('active'))))}
function syncBadge(){const n=profile.favoritePlans.length+profile.history.length,b=$("#libraryCount");if(b){b.hidden=!n;b.textContent=Math.min(99,n)}}
function syncUI(){if(!state.date||state.date<localISODate())state.date=localISODate();$("#dateInput").min=localISODate();$("#dateInput").value=state.date;$("#timeInput").value=state.time;$("#zoneInput").value=state.zone;$("#foodInput").checked=!!state.food;$("#eventsInput").checked=!!state.useEvents;$("#indoorInput").checked=!!state.indoorOnly;$("#noBarsInput").checked=!!state.noBars;$("#avoidVisitedInput").checked=state.avoidVisited!==false;$$('[data-duration]').forEach(b=>b.classList.toggle('active',+b.dataset.duration===+state.duration));$$('[data-budget]').forEach(b=>b.classList.toggle('active',+b.dataset.budget===+state.budget));$$('[data-vibe]').forEach(b=>b.classList.toggle('active',state.vibes.includes(b.dataset.vibe)));$$('[data-adventure]').forEach(b=>b.classList.toggle('active',b.dataset.adventure===state.adventure));$("#durationSummary").textContent=formatDuration(state.duration);$("#budgetSummary").textContent=shortMoney(state.budget);$("#vibeSummary").textContent=state.vibes.map(v=>VIBE_LABELS[v]).join(" + ");$("#quickDate").textContent=shortDate(state.date);$("#quickDuration").textContent=formatDuration(state.duration);$("#quickBudget").textContent=shortMoney(state.budget);$("#quickVibe").textContent=state.vibes.map(v=>VIBE_LABELS[v]).join(" + ");syncBadge();syncPressed()}
$$('[data-duration]').forEach(b=>b.addEventListener('click',()=>{state.duration=+b.dataset.duration;persist();syncUI()}));$$('[data-budget]').forEach(b=>b.addEventListener('click',()=>{state.budget=+b.dataset.budget;persist();syncUI()}));$$('[data-adventure]').forEach(b=>b.addEventListener('click',()=>{state.adventure=b.dataset.adventure;persist();syncUI()}));$$('[data-vibe]').forEach(b=>b.addEventListener('click',()=>{const v=b.dataset.vibe;if(state.vibes.includes(v)){if(state.vibes.length>1)state.vibes=state.vibes.filter(x=>x!==v)}else state.vibes=state.vibes.length>=2?[state.vibes[1],v]:[...state.vibes,v];persist();syncUI()}));
['zoneInput','dateInput','timeInput','foodInput','eventsInput','indoorInput','noBarsInput','avoidVisitedInput'].forEach(id=>$("#"+id)?.addEventListener('change',()=>{state.zone=$("#zoneInput").value;state.date=$("#dateInput").value;state.time=$("#timeInput").value;state.food=$("#foodInput").checked;state.useEvents=$("#eventsInput").checked;state.indoorOnly=$("#indoorInput").checked;state.noBars=$("#noBarsInput").checked;state.avoidVisited=$("#avoidVisitedInput").checked;persist();syncUI()}));$("#prefsToggle")?.addEventListener('click',()=>{$("#prefs").hidden=!$("#prefs").hidden;$("#prefsToggle").setAttribute('aria-expanded',String(!$("#prefs").hidden))});
$("#openFilters")?.addEventListener('click',()=>openOverlay('#filtersOverlay'));$$('[data-open-filter]').forEach(b=>b.addEventListener('click',()=>openOverlay('#filtersOverlay')));$("#filtersForm")?.addEventListener('submit',e=>{e.preventDefault();variationSeed=0;currentAnchor=null;closeOverlay('#filtersOverlay');runPlanner(true)});$("#quickGenerate")?.addEventListener('click',()=>{variationSeed=0;currentAnchor=null;runPlanner(true)});$("#surprise")?.addEventListener('click',()=>{variationSeed+=17+Math.floor(Math.random()*900);currentAnchor=null;runPlanner(true)});$("#moreDates")?.addEventListener('click',()=>{variationSeed++;currentAnchor=null;runPlanner(false)});$("#editFilters")?.addEventListener('click',()=>openOverlay('#filtersOverlay'));
function runPlanner(scroll){const filters=collectFilters();activeFilters=filters;latestPlans=generateDates({places,events,filters,count:3,variationSeed,anchorItem:currentAnchor});rememberShown();renderResults();$("#resultsSection").hidden=false;if(scroll)$("#resultsSection").scrollIntoView({behavior:'smooth',block:'start'})}
function rememberShown(){const ids=latestPlans.flatMap(p=>p.items.map(i=>i.id));profile.recentlyShownItemIds=[...new Set([...ids,...profile.recentlyShownItemIds])].slice(0,90);saveProfile()}
function renderResults(){const grid=$("#resultsGrid"),f=activeFilters||collectFilters();$("#resultsEyebrow").textContent=latestPlans.length===1?"ОДИН СИЛЬНЫЙ ВАРИАНТ":latestPlans.length===2?"ДВА РАЗНЫХ ПОДХОДА":latestPlans.length===3?"ТРИ РАЗНЫХ ПОДХОДА":"РАЗНЫЕ ПОДХОДЫ";$("#filterRecap").innerHTML=`<span>${esc(formatDuration(f.duration))}</span><span>${esc(shortMoney(f.budget))}</span><span>${esc(ZONES[f.zone]||"Москва")}</span>`;if(!latestPlans.length){grid.innerHTML=`<div class="empty"><div class="eyebrow">СЕЙЧАС ХОРОШЕГО ВАРИАНТА НЕТ</div><h3>Не будем ломать условия.</h3><p>Под текущие время, бюджет и пожелания сильного сценария не нашлось.</p><div class="empty-actions"><button class="secondary" data-relax="zone">Расширить район</button><button class="secondary" data-relax="budget">Увеличить бюджет</button><button class="secondary" data-relax="time">Изменить время</button></div></div>`;$$('[data-relax]',grid).forEach(b=>b.addEventListener('click',()=>relax(b.dataset.relax)));return}grid.innerHTML=latestPlans.map(cardHTML).join('');$$('[data-open-plan]',grid).forEach(b=>b.addEventListener('click',()=>openDetail(+b.dataset.openPlan)));$$('[data-save-plan]',grid).forEach(b=>b.addEventListener('click',()=>toggleSave(+b.dataset.savePlan,b)))}
function cardHTML(p,i){const rows=planRows(p),route=rows.slice(0,3).map(r=>r.category.toLowerCase()).join(' → '),fav=profile.favoritePlans.some(x=>x.key===planKey(p)),cover=imageOK(p.coverImage)?p.coverImage:null,img=cover?`<img src="${esc(cover)}" alt="" loading="lazy">`:'';const moods=(activeFilters?.vibes||state.vibes).map(v=>VIBE_LABELS[v]).slice(0,2).join(' · ');return `<article class="date-card"><div class="date-photo ${img?'':'placeholder'}">${img}<div class="photo-top"><span class="serial">№ ${stableNo(p)}</span><button class="save-icon ${fav?'active':''}" data-save-plan="${i}" aria-pressed="${fav}" aria-label="${fav?'Убрать из сохранённых':'Сохранить'}">${fav?'♥':'♡'}</button></div><div class="photo-bottom"><span class="moodline">${esc(moods||p.archetype?.label||'Свидание')}</span></div></div><div class="card-body"><h3>${esc(p.title)}</h3><p class="route-line">${esc(route)}</p><p class="why">${esc(p.why)}</p><div class="card-meta"><b>${esc(formatDuration(p.totalMinutes))}</b><span>${p.items.some(x=>x.costEstimated)?'≈ ':''}${esc(formatMoney(p.totalCost))}</span></div><div class="card-action"><button class="arrow-button" data-open-plan="${i}" aria-label="Открыть свидание">→</button></div></div></article>`}
function relax(type){if(type==='zone')state.zone='any';if(type==='budget')state.budget=state.budget>=15000?999999:15000;if(type==='time')state.duration=Math.min(360,Math.max(240,state.duration+60));persist();syncUI();variationSeed++;runPlanner(false)}
function toggleSave(i,b){const p=latestPlans[i];if(!p)return;const k=planKey(p),idx=profile.favoritePlans.findIndex(x=>x.key===k);if(idx>=0)profile.favoritePlans.splice(idx,1);else profile.favoritePlans.unshift(snapshotPlan(p,activeFilters||collectFilters()));saveProfile();const active=idx<0;if(b){b.classList.toggle('active',active);b.textContent=active?'♥':'♡';b.setAttribute('aria-pressed',String(active))}}
function chapterRole(i,n){if(i===0)return'Начало';if(i===n-1)return'Финал';if(n===4&&i===1)return'Развитие';return'Главная часть'}
function openDetail(i){activePlanIndex=i;renderDetail();openOverlay('#detailOverlay')}
function renderDetail(){const p=latestPlans[activePlanIndex];if(!p)return;const rows=planRows(p),cover=imageOK(p.coverImage)?p.coverImage:null,img=cover?`<img src="${esc(cover)}" alt="">`:'';$("#detailScreenTitle").textContent=`Свидание № ${stableNo(p)}`;$("#detailContent").innerHTML=`<div class="detail-hero"><div class="hero-img ${img?'':'placeholder'}">${img}</div><div class="detail-copy"><div class="eyebrow">СВИДАНИЕ № ${stableNo(p)} · ${esc(p.archetype?.label||'')}</div><h2>${esc(p.title)}</h2><p>${esc(p.story)}</p><div class="detail-meta"><span>${esc(formatDuration(p.totalMinutes))}</span><span>${p.items.some(x=>x.costEstimated)?'≈ ':''}${esc(formatMoney(p.totalCost))}</span><span>${p.items.length} главы</span></div></div></div><div class="why-box"><b>ПОЧЕМУ ПОДХОДИТ</b><p>${esc(p.why)}</p></div><section class="chapters"><h3>План вечера</h3>${rows.map((r,i)=>chapterHTML(r,i,rows.length)).join('')}</section>`;$("#detailSave").textContent=profile.favoritePlans.some(x=>x.key===planKey(p))?'♥':'♡';$("#detailSave").onclick=e=>toggleSave(activePlanIndex,e.currentTarget);$("#chooseDate").onclick=()=>{recordHistory(p);renderInvite();openOverlay('#inviteOverlay')};$$('[data-replace]',$("#detailContent")).forEach(b=>b.addEventListener('click',()=>openReplace(+b.dataset.replace)));$$('[data-around]',$("#detailContent")).forEach(b=>b.addEventListener('click',()=>{currentAnchor=p.items[+b.dataset.around];variationSeed++;closeOverlay('#detailOverlay');runPlanner(true)}));$$('[data-like-item]',$("#detailContent")).forEach(b=>b.addEventListener('click',()=>toggleItem(p.items[+b.dataset.likeItem],b)));$$('[data-dislike-item]',$("#detailContent")).forEach(b=>b.addEventListener('click',()=>dislikeItem(p.items[+b.dataset.dislikeItem],b)))}
function chapterHTML(r,i,n){const links=[r.officialUrl&&`<a href="${esc(r.officialUrl)}" target="_blank" rel="noreferrer">Сайт ↗</a>`,r.sourceUrl&&`<a href="${esc(r.sourceUrl)}" target="_blank" rel="noreferrer">Подробнее ↗</a>`].filter(Boolean).join('');const liked=Boolean(profile.favoriteItems[r.itemId]),disliked=profile.dislikedItemIds.includes(r.itemId);return `<article class="chapter"><div class="chapter-no">${String(i+1).padStart(2,'0')}</div><div><span class="chapter-role">${chapterRole(i,n).toUpperCase()}</span><h4>${esc(r.title)}</h4><p>${esc(r.description)}</p><div class="chapter-meta">${esc(r.duration)} · ${r.costEstimated?'≈ ':''}${esc(r.cost)}</div><div class="chapter-actions"><button class="chapter-primary" data-replace="${i}">Заменить эту главу</button><button class="icon-action" data-around="${i}" aria-label="Собрать свидание вокруг этого места">✦</button><button class="icon-action" data-like-item="${i}" aria-label="${liked?'Убрать место из любимых':'Сохранить место'}">${liked?'♥':'♡'}</button><button class="icon-action" data-dislike-item="${i}" aria-label="${disliked?'Место уже исключено':'Больше не предлагать это место'}" ${disliked?'disabled':''}>${disliked?'✓':'⊘'}</button>${links}</div></div></article>`}
function toggleItem(item,b){if(profile.favoriteItems[item.id])delete profile.favoriteItems[item.id];else profile.favoriteItems[item.id]={id:item.id,title:item.title,category:item.category,savedAt:new Date().toISOString()};saveProfile();b.textContent=profile.favoriteItems[item.id]?'♥':'♡';b.setAttribute('aria-label',profile.favoriteItems[item.id]?'Убрать место из любимых':'Сохранить место')}
function dislikeItem(item,b){if(!profile.dislikedItemIds.includes(item.id))profile.dislikedItemIds.unshift(item.id);profile.dislikedItemIds=profile.dislikedItemIds.slice(0,150);saveProfile();b.disabled=true;b.textContent='✓';b.setAttribute('aria-label','Место уже исключено')}
function replacementWhy(label,item,current){const cat=item.category===current.category?'тот же характер главы':'другой характер главы';const cost=Number(item.costForTwo||0)<Number(current.costForTwo||0)?'и мягче по бюджету':Number(item.costForTwo||0)>Number(current.costForTwo||0)?'с чуть большим акцентом на впечатление':'без заметного изменения бюджета';return `${label}: ${cat} ${cost}.`}
function openReplace(itemIndex){const p=latestPlans[activePlanIndex];if(!p)return;const candidates=[];for(let s=1;s<=7&&candidates.length<4;s++){const next=replacePlanItem({plan:p,itemIndex,places,events,filters:activeFilters,variationSeed:variationSeed+s*11});if(next.items[itemIndex]?.id!==p.items[itemIndex]?.id&&!candidates.some(x=>x.items[itemIndex].id===next.items[itemIndex].id))candidates.push(next)}const labels=['Ближе к исходному','Атмосфернее','Спокойнее','Необычнее'];$("#replaceTitle").textContent='Чем заменить эту главу?';$("#replaceList").innerHTML=candidates.length?candidates.map((plan,idx)=>{const item=plan.items[itemIndex],label=labels[idx]||'Другой вариант',img=imageOK(item.image)?`<img src="${esc(item.image)}" alt="" loading="lazy">`:'';return `<article class="replace-card"><div class="replace-thumb">${img}</div><div><div class="eyebrow">${label}</div><h4>${esc(item.title)}</h4><p>${esc(replacementWhy(label,item,p.items[itemIndex]))}</p><div class="replace-meta">${item.costEstimated?'≈ ':''}${esc(formatMoney(item.costForTwo||0))}</div><button data-pick-replace="${idx}">Выбрать эту главу</button></div></article>`}).join(''):`<div class="empty"><h3>Сильной замены нет.</h3><p>Оставим эту главу как есть, чтобы не ухудшать сценарий.</p></div>`;$$('[data-pick-replace]').forEach(b=>b.addEventListener('click',()=>{latestPlans[activePlanIndex]=candidates[+b.dataset.pickReplace];variationSeed+=13;closeOverlay('#replaceOverlay');renderResults();renderDetail()}));openOverlay('#replaceOverlay')}
function recordHistory(p){const snap=snapshotPlan(p,activeFilters);profile.history=profile.history.filter(x=>x.key!==snap.key);profile.history.unshift(snap);profile.history=profile.history.slice(0,30);saveProfile()}
function renderLibrary(tab='saved'){const saved=profile.favoritePlans,history=profile.history,items=Object.values(profile.favoriteItems);$$('[data-library-tab]').forEach(b=>b.classList.toggle('active',b.dataset.libraryTab===tab));const list=tab==='saved'?saved:tab==='history'?history:items;$("#libraryContent").innerHTML=list.length?list.map(entry=>tab==='places'?`<article class="mini-card"><div class="mini-placeholder"></div><div><h4>${esc(entry.title)}</h4><p>${esc(entry.category||'Место')}</p></div></article>`:`<article class="mini-card">${imageOK(entry.coverImage)?`<img src="${esc(entry.coverImage)}" alt="" loading="lazy">`:`<div class="mini-placeholder"></div>`}<div><div class="eyebrow">${tab==='history'?esc(humanDate(entry.date)):esc(entry.archetype||'Свидание')}</div><h4>${esc(entry.title)}</h4><p>${esc(formatDuration(entry.totalMinutes))} · ${esc(formatMoney(entry.totalCost))}</p></div></article>`).join(''):`<div class="empty"><h3>Пока пусто.</h3><p>Сохраняй свидания и места — они появятся здесь.</p></div>`}
$("#libraryButton")?.addEventListener('click',()=>{renderLibrary();openOverlay('#libraryOverlay')});$("#navLibrary")?.addEventListener('click',()=>{renderLibrary();openOverlay('#libraryOverlay')});$$('[data-library-tab]').forEach(b=>b.addEventListener('click',()=>renderLibrary(b.dataset.libraryTab)));
function renderProfile(){const v=state.vibes.map(x=>VIBE_LABELS[x]).join(' + '),adv={safe:'Проверенное',balanced:'Баланс',wild:'Смелее'}[state.adventure],favPlaces=Object.values(profile.favoriteItems).slice(0,4);$("#profileContent").innerHTML=`<div class="profile"><div class="eyebrow">ПРОФИЛЬ</div><h2>Ваш вкус<br><em>уже складывается.</em></h2><p>Предпочтения хранятся локально и помогают меньше повторяться.</p><div class="profile-summary"><div><b>${profile.history.length}</b><span>выбрано свиданий</span></div><div><b>${Object.keys(profile.favoriteItems).length}</b><span>любимых мест</span></div></div><div class="taste"><div class="eyebrow">СЕЙЧАС ВАЖНО</div><h3>${esc(v)}</h3><div class="chips"><span>${esc(ZONES[state.zone])}</span><span>${esc(adv)}</span>${favPlaces.map(x=>`<span>${esc(x.title)}</span>`).join('')}</div></div><div class="profile-links"><button id="profileFilters">Настроить предпочтения</button></div></div>`;$("#profileFilters")?.addEventListener('click',()=>{closeOverlay('#profileOverlay');openOverlay('#filtersOverlay')})}
$("#navProfile")?.addEventListener('click',()=>{renderProfile();openOverlay('#profileOverlay')});$("#navDiscover")?.addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}));
function renderInvite(){const p=latestPlans[activePlanIndex],f=activeFilters;if(!p||!f)return;const d=new Date(`${f.date}T12:00:00`),day=String(d.getDate()).padStart(2,'0'),month=new Intl.DateTimeFormat('ru-RU',{month:'short'}).format(d).replace('.','').toUpperCase(),note=$("#inviteNote").value.trim()||'Просто освободи вечер. Остальное уже придумано.';$("#poster").className=`poster ${inviteTheme==='night'?'night':inviteTheme==='minimal'?'minimal':''}`;$("#poster").innerHTML=`<div class="poster-top"><span>1001 DATES</span><span>№ ${stableNo(p)}</span></div><div class="poster-date"><strong>${day}</strong><div><span>${esc(month)}</span><span>${esc(f.time)}</span></div></div><div class="poster-main"><span>У МЕНЯ ЕСТЬ ПЛАН НА НАС</span><h3>${esc(p.title)}</h3><p>${esc(note)}</p></div><div class="poster-foot"><div><span>НА СКОЛЬКО</span><b>${esc(formatDuration(p.totalMinutes))}</b></div><div><span>ПЛАН</span><b>${inviteReveal==='full'?`${p.items.length} главы`:'сюрприз'}</b></div></div>`}
$$('[data-theme]').forEach(b=>b.addEventListener('click',()=>{inviteTheme=b.dataset.theme;$$('[data-theme]').forEach(x=>x.classList.toggle('active',x===b));syncPressed();renderInvite()}));$$('[data-reveal]').forEach(b=>b.addEventListener('click',()=>{inviteReveal=b.dataset.reveal;$$('[data-reveal]').forEach(x=>x.classList.toggle('active',x===b));syncPressed();renderInvite()}));$("#inviteNote")?.addEventListener('input',renderInvite);
function inviteText(){const p=latestPlans[activePlanIndex],f=activeFilters;if(!p)return'';return `У меня есть план на нас ♡\n\n${p.title}\n${humanDate(f.date)}, ${f.time}\n${formatDuration(p.totalMinutes)}\n\n1001 Dates`}
$("#copyInvite")?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(inviteText());$("#copyInvite").textContent='Скопировано ✓';setTimeout(()=>$("#copyInvite").textContent='Скопировать',1200)}catch{}});$("#calendarInvite")?.addEventListener('click',()=>{const p=latestPlans[activePlanIndex],f=activeFilters,start=new Date(`${f.date}T${f.time}:00`),end=new Date(start.getTime()+p.totalMinutes*60000),stamp=d=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z'),ics=`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nBEGIN:VEVENT\r\nDTSTART:${stamp(start)}\r\nDTEND:${stamp(end)}\r\nSUMMARY:${p.title}\r\nEND:VEVENT\r\nEND:VCALENDAR`,blob=new Blob([ics],{type:'text/calendar'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='1001-dates.ics';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)});
async function ensureCanvas(){if(window.html2canvas)return window.html2canvas;await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/html2canvas@1.4.1/dist/html2canvas.min.js';s.onload=res;s.onerror=rej;document.head.append(s)});return window.html2canvas}
async function posterBlob(){const h=await ensureCanvas(),canvas=await h($("#poster"),{backgroundColor:null,scale:Math.max(2,window.devicePixelRatio||2),useCORS:true,logging:false});return await new Promise((res,rej)=>canvas.toBlob(b=>b?res(b):rej(new Error('PNG failed')),'image/png'))}
$("#shareInvite")?.addEventListener('click',async()=>{try{const blob=await posterBlob(),file=new File([blob],'1001-dates.png',{type:'image/png'});if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]})))return navigator.share({title:'1001 Dates',text:inviteText(),files:[file]});const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='1001-dates.png';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}catch{try{await navigator.clipboard.writeText(inviteText())}catch{}}});
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js?v=final3',{updateViaCache:'none'}).catch(()=>{});syncUI();renderLibrary();
