import * as base from "./engine.js?base=final3";

const CENTER={lat:55.7558,lon:37.6173};
const RADIUS_KM=30;
const GENERIC=new Set(["сеть","ресторан","ресторанов","кафе","кофейня","кофеен","бар","баров","паб","бистро","клуб","клубов","гастробар","пиццерия","кондитерская","restaurant","cafe","coffee","bar","pub","bistro","club"]);
const GENERIC_TITLE=/^(?:торговый центр|торгово-развлекательный центр|торговый комплекс|трц|тц|развлекательный центр|культурный центр|арт[- ]?пространство|пространство|центр|кафе|кофейня|ресторан|бар|паб|парк|сад|музей|галерея|выставка|театр|кинотеатр|клуб)$/i;
const COVER_WEIGHT={art:11,viewpoint:10,activity:9,dinner:8,dessert:7,cafe:6,walk:5,event:3,bar:3};
const VIBE_WORD={romantic:"романтичный",fun:"живой",unusual:"необычный",calm:"спокойный",active:"активный"};
const CHAPTER_PHRASE={art:"искусство и разговор",viewpoint:"красивый вид на город",activity:"совместное действие",dinner:"ужин без спешки",dessert:"лёгкий сладкий финал",cafe:"спокойное начало за кофе",walk:"прогулка с временем на разговор",event:"одно актуальное событие",bar:"продолжение вечера"};

function key(value=""){const text=String(value).toLowerCase().replace(/ё/g,"е").replace(/[«»“”„"']/g,"").replace(/[.,:;!?–—/\\-]+/g," ").replace(/\s+/g," ").trim();const tokens=text.split(/\s+/).filter((x)=>x.length>1&&!GENERIC.has(x));return tokens.join(" ")||text;}
function cleanTitle(value=""){return String(value).toLowerCase().replace(/ё/g,"е").replace(/[«»“”„"']/g,"").replace(/[.,:;!?–—/\\]+/g," ").replace(/\s+/g," ").trim();}
function coords(item){const a=item?.coords?.lat,b=item?.coords?.lon;if(a==null||b==null)return null;const lat=Number(a),lon=Number(b);if(!Number.isFinite(lat)||!Number.isFinite(lon)||lat===0||lon===0||Math.abs(lat)>90||Math.abs(lon)>180)return null;return {lat,lon};}
function distanceKm(a,b){const R=6371,r=(x)=>x*Math.PI/180,dp=r(b.lat-a.lat),dl=r(b.lon-a.lon),q=Math.sin(dp/2)**2+Math.cos(r(a.lat))*Math.cos(r(b.lat))*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(q));}
function live(item){return String(item?.id||"").startsWith("kudago-");}
function titleSane(item){const t=cleanTitle(item?.title||"");if(!t||GENERIC_TITLE.test(t))return false;if(/^\s*сеть\s+/.test(t)&&(!item.address||/^(москва|центр москвы)$/i.test(String(item.address))))return false;if(/детск(?:ий|ая|ое|ие)|для детей/i.test(t))return false;if(item.category==="event"&&(/^\d[\d\s./-]*$/.test(t)||t.replace(/[^a-zа-я0-9]/gi,"").length<4))return false;if(item.category==="cafe"&&/(собор|храм|церков|музей|галере|парк|сад|театр|стадион|торгов)/i.test(t))return false;if(item.category==="bar"&&/(парк|сад|музей|галере|собор|храм|церков|стадион|торгов)/i.test(t))return false;if(item.category==="dinner"&&/(парк|сад|музей|галере|собор|храм|церков|стадион|торгов)/i.test(t)&&!/(ресторан|кафе|бистро|гастро)/i.test(t))return false;if(item.category==="dessert"&&/(фабрик|завод|парк|сад|музей|галере|театр|трц|торгов)/i.test(t)&&!/(кондитер|десерт|морож|джелат|шоколадн|пекар|cake|gelato)/i.test(t))return false;return true;}
function validLive(item){const c=coords(item);return Boolean(titleSane(item)&&c&&distanceKm(CENTER,c)<=RADIUS_KM);}
function selectSource(items,minimum){const clean=(items||[]).filter(titleSane),liveItems=clean.filter(live).filter(validLive);return liveItems.length>=minimum?liveItems:clean.filter((x)=>!live(x)||validLive(x));}
function prepare(items,filters,minimum,anchorItem=null){const original=items||[],idKey=new Map(original.map((x)=>[x.id,key(x.title)]));const recentIds=new Set(filters?.recentlyShownItemIds||[]);const recentKeys=new Set([...recentIds].map((id)=>idKey.get(id)).filter(Boolean));for(const k of filters?.recentlyShownItemKeys||[])recentKeys.add(k);const anchorKey=anchorItem?key(anchorItem.title):(filters?.anchorItem?key(filters.anchorItem.title):null);const source=selectSource(original,minimum).filter((x)=>anchorKey===key(x.title)||!recentKeys.has(key(x.title)));const best=new Map();for(const item of source){const k=key(item.title),prev=best.get(k);const score=(item.sourceUrl||item.officialUrl?10:0)+Number(item.quality||0);const prevScore=prev?((prev.sourceUrl||prev.officialUrl?10:0)+Number(prev.quality||0)):-Infinity;if(!prev||score>prevScore)best.set(k,item);}return [...best.values()];}
function guardedArgs(args){const filters=args?.filters||{},anchorItem=args?.anchorItem||null;return {...args,places:prepare(args?.places||[],filters,100,anchorItem),events:prepare(args?.events||[],filters,30,anchorItem)};}
function imageSuitable(item){const src=String(item?.image||"");if(!/^https?:\/\//i.test(src)||/logo|poster|banner|afisha|афиш|sprite|icon/i.test(src))return false;return titleSane(item);}
function coverScore(item,filters,index){let score=(COVER_WEIGHT[item?.category]||4)+Math.min(10,Number(item?.quality||0));if((filters?.vibes||[]).some((v)=>item?.vibes?.includes?.(v)))score+=4;if(item?.costEstimated)score-=.5;if(index===0)score+=1;if(/торгов|трц|тц|молл|mall/i.test(String(item?.title||"")))score-=14;return score;}
function chooseCover(plan,filters){const ranked=(plan?.items||[]).map((item,index)=>({item,index,score:coverScore(item,filters,index)})).filter(({item})=>imageSuitable(item)).sort((a,b)=>b.score-a.score);return ranked[0]?.item?.image||(/^https?:\/\//i.test(String(plan?.coverImage||""))?plan.coverImage:null);}
function durationPhrase(minutes){const h=Math.round(Number(minutes||0)/60);return h===2?"2 часа":h===3?"3 часа":h===4?"4 часа":h===6?"6 часов":base.formatDuration(minutes);}
function moodPhrase(filters){const words=(filters?.vibes||[]).slice(0,2).map((v)=>VIBE_WORD[v]).filter(Boolean);return words.length?words.join(" и "):"цельный";}
function constraintPhrase(filters){const parts=[];if(filters?.noBars)parts.push("без баров");if(filters?.indoorOnly)parts.push("только внутри");if(filters?.food===false)parts.push("без обязательной еды");if(filters?.useEvents===false)parts.push("без привязки к афише");return parts.length?` Условия ${parts.join(", ")} сохранены.`:"";}
function editorialWhy(plan,filters){const items=plan?.items||[],first=CHAPTER_PHRASE[items[0]?.category]||"лёгкое начало",middle=CHAPTER_PHRASE[items[Math.floor((items.length-1)/2)]?.category]||"главное впечатление",last=CHAPTER_PHRASE[items.at(-1)?.category]||"спокойный финал";const zone=filters?.zone&&filters.zone!=="any"?" в выбранном районе":"";return `Вы выбрали ${moodPhrase(filters)} вечер на ${durationPhrase(filters?.duration)}${zone}. Поэтому здесь ${first}, ${middle} и ${last}.${constraintPhrase(filters)}`;}
function editorialStory(plan,filters){const items=plan?.items||[],middle=items[Math.floor(items.length/2)],start=CHAPTER_PHRASE[items[0]?.category]||"лёгкое начало",focus=CHAPTER_PHRASE[middle?.category]||"одно главное впечатление",finish=CHAPTER_PHRASE[items.at(-1)?.category]||"финал без спешки";return `Ритм вечера простой: ${start}, затем ${focus}. В конце — ${finish}, чтобы свидание не ощущалось набором случайных точек.`;}
function enrichPlan(plan,filters){if(!plan)return plan;return {...plan,coverImage:chooseCover(plan,filters),why:editorialWhy(plan,filters),story:editorialStory(plan,filters)};}

export function generateDates(args){const guarded=guardedArgs(args),filters=guarded.filters||{};return base.generateDates(guarded).map((plan)=>enrichPlan(plan,filters));}
export function replacePlanItem(args){const guarded=guardedArgs(args),filters=guarded.filters||{};return enrichPlan(base.replacePlanItem(guarded),filters);}
export const planRows=base.planRows;
export const formatMoney=base.formatMoney;
export const formatDuration=base.formatDuration;
export const estimateScenarioCount=base.estimateScenarioCount;
export const auditPlanConstraints=base.auditPlanConstraints;
export const auditPlanGeography=base.auditPlanGeography;
